### ISSUE TITLE
Downloading larger PDF with content-fetch fails

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2111]
Seeing this error as the PDF body is too large:

```
DEFAULT 2023-04-25T02:53:35Z parse-page {
DEFAULT 2023-04-25T02:53:35Z url: 'https://s29.q4cdn.com/969268860/files/doc_financials/2022/ar/2022-LiveRamp-Annual-Report.pdf',
DEFAULT 2023-04-25T02:53:35Z userId: undefined,
DEFAULT 2023-04-25T02:53:35Z articleSavingRequestId: 'd3341082-0fc6-47ba-95f0-7f4f513e0c25',
DEFAULT 2023-04-25T02:53:35Z labels: { source: 'parseContent' },
DEFAULT 2023-04-25T02:53:35Z state: undefined,
DEFAULT 2023-04-25T02:53:35Z labelsToAdd: undefined,
DEFAULT 2023-04-25T02:53:35Z error: 'The "url" argument must be of type string. Received undefined',
DEFAULT 2023-04-25T02:53:35Z fetchContentTime: 4612
DEFAULT 2023-04-25T02:53:35Z }
DEFAULT 2023-04-25T02:53:35Z (node:39) UnhandledPromiseRejectionWarning: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
DEFAULT 2023-04-25T02:53:35Z at RedirectableRequest.write (/app/node_modules/follow-redirects/index.js:102:24)
DEFAULT 2023-04-25T02:53:35Z at RedirectableRequest.end (/app/node_modules/follow-redirects/index.js:127:10)
DEFAULT 2023-04-25T02:53:35Z at dispatchHttpRequest (/app/node_modules/axios/lib/adapters/http.js:421:11)
DEFAULT 2023-04-25T02:53:35Z at new Promise (<anonymous>)
DEFAULT 2023-04-25T02:53:35Z at httpAdapter (/app/node_modules/axios/lib/adapters/http.js:49:10)
DEFAULT 2023-04-25T02:53:35Z at dispatchRequest (/app/node_modules/axios/lib/core/dispatchRequest.js:58:10)
DEFAULT 2023-04-25T02:53:35Z at Axios.request (/app/node_modules/axios/lib/core/Axios.js:109:15)
DEFAULT 2023-04-25T02:53:35Z at Axios.httpMethod [as post] (/app/node_modules/axios/lib/core/Axios.js:144:19)
DEFAULT 2023-04-25T02:53:35Z at Function.wrap [as post] (/app/node_modules/axios/lib/helpers/bind.js:9:15)
DEFAULT 2023-04-25T02:53:35Z at sendSavePageMutation (/app/packages/puppeteer-parse/index.js:226:32)
```

**Comment by Podginator** [comment]
Closing due to age, and the self-hosted nature of Omnivore. Done as a batch action. If this issue still exists, please reopen it.
