### ISSUE TITLE
omnivore-api permission denied. 

### ISSUE THREAD

**Issue by sam1am** [omnivore-app/omnivore#2219]
When following the instructions in the readme I get permission denied from omnivore api and it crashes. 

Here is the output I am seeing: 

```
omnivore-api            | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
omnivore-postgres       | 2023-05-18 17:38:48.673 UTC [1403] ERROR:  permission denied to create extension "uuid-ossp"
omnivore-postgres       | 2023-05-18 17:38:48.673 UTC [1403] HINT:  Must be superuser to create this extension.
omnivore-postgres       | 2023-05-18 17:38:48.673 UTC [1403] STATEMENT:  CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
omnivore-api            | query: SHOW server_version;
omnivore-api            | elastic info:  {
omnivore-api            |   body: {
omnivore-api            |     name: '9b929c2b994a',
omnivore-api            |     cluster_name: 'docker-cluster',
omnivore-api            |     cluster_uuid: '1moS0LgrQg-nBzvm61ULqg',
omnivore-api            |     version: {
omnivore-api            |       number: '7.17.1',
omnivore-api            |       build_flavor: 'default',
omnivore-api            |       build_type: 'docker',
omnivore-api            |       build_hash: 'e5acb99f822233d62d6444ce45a4543dc1c8059a',
omnivore-api            |       build_date: '2022-02-23T22:20:54.153567231Z',
omnivore-api            |       build_snapshot: false,
omnivore-api            |       lucene_version: '8.11.1',
omnivore-api            |       minimum_wire_compatibility_version: '6.8.0',
omnivore-api            |       minimum_index_compatibility_version: '6.0.0-beta1'
omnivore-api            |     },
omnivore-api            |     tagline: 'You Know, for Search'
omnivore-api            |   },
omnivore-api            |   statusCode: 200,
omnivore-api            |   headers: {
omnivore-api            |     'x-elastic-product': 'Elasticsearch',
omnivore-api            |     warning: '299 Elasticsearch-7.17.1-e5acb99f822233d62d6444ce45a4543dc1c8059a "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."',
omnivore-api            |     'content-type': 'application/json; charset=UTF-8',
omnivore-api            |     'content-length': '546'
omnivore-api            |   },
omnivore-api            |   meta: {
omnivore-api            |     context: null,
omnivore-api            |     request: { params: [Object], options: {}, id: 1 },
omnivore-api            |     name: 'elasticsearch-js',
omnivore-api            |     connection: {
omnivore-api            |       url: 'http://elastic:9200/',
omnivore-api            |       id: 'http://elastic:9200/',
omnivore-api            |       headers: {},
omnivore-api            |       deadCount: 0,
omnivore-api            |       resurrectTimeout: 0,
omnivore-api            |       _openRequests: 0,
omnivore-api            |       status: 'alive',
omnivore-api            |       roles: [Object]
omnivore-api            |     },
omnivore-api            |     attempts: 0,
omnivore-api            |     aborted: false
omnivore-api            |   }
omnivore-api            | }
omnivore-api            | creating index...
omnivore-api            | failed to init elasticsearch Error: ENOENT: no such file or directory, open '/app/packages/api/dist/elastic/../../../db/elastic_migrations/index_settings.json'
omnivore-api            |     at Object.openSync (fs.js:497:3)
omnivore-api            |     at readFileSync (fs.js:393:35)
omnivore-api            |     at createIndex (/app/packages/api/dist/elastic/index.js:20:49)
omnivore-api            |     at initElasticsearch (/app/packages/api/dist/elastic/index.js:37:19)
omnivore-api            |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
omnivore-api            |     at async main (/app/packages/api/dist/server.js:182:5) {
omnivore-api            |   errno: -2,
omnivore-api            |   syscall: 'open',
omnivore-api            |   code: 'ENOENT',
omnivore-api            |   path: '/app/packages/api/dist/elastic/../../../db/elastic_migrations/index_settings.json'
omnivore-api            | }
omnivore-api            | (node:39) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/app/packages/api/dist/elastic/../../../db/elastic_migrations/index_settings.json'
omnivore-api            |     at Object.openSync (fs.js:497:3)
omnivore-api            |     at readFileSync (fs.js:393:35)
omnivore-api            |     at createIndex (/app/packages/api/dist/elastic/index.js:20:49)
omnivore-api            |     at initElasticsearch (/app/packages/api/dist/elastic/index.js:37:19)
omnivore-api            |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
omnivore-api            |     at async main (/app/packages/api/dist/server.js:182:5)
omnivore-api            | (Use `node --trace-warnings ...` to show where the warning was created)
omnivore-api            | (node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
omnivore-api            | (node:39) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
omnivore-api            | Done in 14.76s.
omnivore-api            | Done in 15.18s.
dependency failed to start: container omnivore-api exited (0)
```

**Comment by jacksonh** [comment]
Hi @sam1am can you tell if the migrations container ran? I think that will create the elastic index, and then this file wont be looked for on initialization.

**Comment by jacksonh** [comment]
Closing this one, pretty sure the user was not created during migration
