### ISSUE TITLE
Error when deploying via docker

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [omnivore-app/omnivore#2239]
Hi,

I followed the steps 

```
git clone https://github.com/omnivore-app/omnivore
cd omnivore
docker-compose up
```

and I am getting this error at the end of the final command. My container's are not up either and I cannot find /usr/share/elasticsearch/data/nodes in the filesystem

```
omnivore-elastic        | {"type": "server", "timestamp": "2023-05-22T21:57:59,561Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "6bfd6cabbd44", "message": "uncaught exception in thread [main]", 
omnivore-elastic        | "stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "Caused by: org.elasticsearch.ElasticsearchException: failed to bind service",
omnivore-elastic        | "at org.elasticsearch.node.Node.<init>(Node.java:1093) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "... 6 more",
omnivore-elastic        | "Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",
omnivore-elastic        | "at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
omnivore-elastic        | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]",
omnivore-elastic        | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
omnivore-elastic        | "at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397) ~[?:?]",
omnivore-elastic        | "at java.nio.file.Files.createDirectory(Files.java:700) ~[?:?]",
omnivore-elastic        | "at java.nio.file.Files.createAndCheckIsDirectory(Files.java:807) ~[?:?]",
omnivore-elastic        | "at java.nio.file.Files.createDirectories(Files.java:793) ~[?:?]",
omnivore-elastic        | "at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:300) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:224) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:298) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.node.Node.<init>(Node.java:429) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.1.jar:7.17.1]",
omnivore-elastic        | "... 6 more"] }
omnivore-elastic        | uncaught exception in thread [main]
omnivore-elastic        | ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
omnivore-elastic        | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
omnivore-elastic        | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
omnivore-elastic        | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
omnivore-elastic        | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
omnivore-elastic        | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
omnivore-elastic        | 	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
omnivore-elastic        | 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
omnivore-elastic        | 	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
omnivore-elastic        | 	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:300)
omnivore-elastic        | 	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:224)
omnivore-elastic        | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:298)
omnivore-elastic        | 	at org.elasticsearch.node.Node.<init>(Node.java:429)
omnivore-elastic        | 	at org.elasticsearch.node.Node.<init>(Node.java:309)
omnivore-elastic        | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
omnivore-elastic        | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
omnivore-elastic        | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
omnivore-elastic        | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
omnivore-elastic        | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
omnivore-elastic        | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
omnivore-elastic        | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
omnivore-elastic        | 	at org.elasticsearch.cli.Command.main(Command.java:77)
omnivore-elastic        | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)
omnivore-elastic        | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
omnivore-elastic        | For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log
omnivore-elastic exited with code 1
dependency failed to start: container omnivore-elastic exited (1)

```

**Comment by jacksonh** [comment]
Hi @Gandalf-the-Blue can I ask is this on Windows? I'm wondering if its related to docker volumes.

**Comment by Gandalf-the-Blue** [comment]
Nope. Deploying on OpenMediaVault (Debian based) via Portainer.

**Comment by Psionyde** [comment]
@Gandalf-the-Blue /usr/share/elasticsearch/data/nodes is mapped to ./.docker/elastic-data (docker-compose.yml:55)

I'd suspect ./.docker/elastic-data either doesn't exist, or isn't writable by the container

**Comment by liuchenbaidu** [comment]
I have encountered the same situation.

**Comment by jacksonh** [comment]
@liuchenbaidu what system are you trying to deploy on?

**Comment by lemon22333** [comment]
try   `chmod 777 ./.docker/elastic-data`

**Comment by Aincvy** [comment]
`chown -R [user:group] .docker` works for me.

Maybe we need to manually create the directory before running the docker compose up command. For example, execute mkdir -p ./.docker/elastic-data first.

**Comment by jacksonh** [comment]
I'll close this as we no longer have elastic
