### ISSUE TITLE
RSS/Newsletter: Separate out into separate feed.

### ISSUE THREAD

**Issue by Podginator** [omnivore-app/omnivore#2595]
Hi, 

I like the new RSS Feature. However, I'd prefer a view where I acn go through the RSS feed and select which article I'd like to read later. At the moment, adding an RSS feed or newsletter just sends things automatically to my Inbox. 

I'd like to have a way to keep my inbox separate, as those are things I'd actually like to read. Not every article on RSS is something I'd like to read. 

In the same vein, perhaps the RSS feature could have a paired back view? Rather than parsing each article, simply extracting the title and description into a list that I can choose to add to my inbox?

**Comment by tdmarchetta** [comment]
@Podginator, Could you let me know how you can access to RSS service?

**Comment by jacksonh** [comment]
> @Podginator, Could you let me know how you can access to RSS service?

We're just betaing it now but check out https://omnivore.app/settings/feeds to add a feed.

**Comment by tdmarchetta** [comment]
@Podginator, thank you for giving me the link; however, every time I access and receiving an error message. 

"Application error: a client-side exception has occurred (see the browser console for more information)."

```
framework-45ce3d09104a2cae.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at W (feeds-433f504e5391bc24.js:1:19339)
    at oo (framework-45ce3d09104a2cae.js:1:59415)
    at Wo (framework-45ce3d09104a2cae.js:1:68982)
    at Ku (framework-45ce3d09104a2cae.js:1:112706)
    at Li (framework-45ce3d09104a2cae.js:1:98956)
    at Ni (framework-45ce3d09104a2cae.js:1:98884)
    at Pi (framework-45ce3d09104a2cae.js:1:98747)
    at bi (framework-45ce3d09104a2cae.js:1:95713)
    at framework-45ce3d09104a2cae.js:1:45207
    at t.unstable_runWithPriority (framework-45ce3d09104a2cae.js:1:129349)
cu @ framework-45ce3d09104a2cae.js:1
a.componentDidCatch.n.callback @ framework-45ce3d09104a2cae.js:1
ha @ framework-45ce3d09104a2cae.js:1
gu @ framework-45ce3d09104a2cae.js:1
Ri @ framework-45ce3d09104a2cae.js:1
t.unstable_runWithPriority @ framework-45ce3d09104a2cae.js:1
Ql @ framework-45ce3d09104a2cae.js:1
Oi @ framework-45ce3d09104a2cae.js:1
bi @ framework-45ce3d09104a2cae.js:1
(anonymous) @ framework-45ce3d09104a2cae.js:1
t.unstable_runWithPriority @ framework-45ce3d09104a2cae.js:1
Ql @ framework-45ce3d09104a2cae.js:1
Yl @ framework-45ce3d09104a2cae.js:1
Kl @ framework-45ce3d09104a2cae.js:1
hi @ framework-45ce3d09104a2cae.js:1
zo @ framework-45ce3d09104a2cae.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
b @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
o @ 9857-d465aa09f39b4116.js:1
Promise.then (async)
c @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
i @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
gu @ framework-45ce3d09104a2cae.js:1
Ri @ framework-45ce3d09104a2cae.js:1
t.unstable_runWithPriority @ framework-45ce3d09104a2cae.js:1
Ql @ framework-45ce3d09104a2cae.js:1
Oi @ framework-45ce3d09104a2cae.js:1
bi @ framework-45ce3d09104a2cae.js:1
hi @ framework-45ce3d09104a2cae.js:1
es @ framework-45ce3d09104a2cae.js:1
(anonymous) @ framework-45ce3d09104a2cae.js:1
ki @ framework-45ce3d09104a2cae.js:1
os @ framework-45ce3d09104a2cae.js:1
t.hydrate @ framework-45ce3d09104a2cae.js:1
h.default.createElement.callbacks @ main-7191483071d7e180.js:1
fe @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
l @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
P.forEach.e.<computed> @ main-7191483071d7e180.js:1
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
te @ main-7191483071d7e180.js:1
ee @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
l @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
P.forEach.e.<computed> @ main-7191483071d7e180.js:1
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
Promise.then (async)
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
Promise.then (async)
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
Z @ main-7191483071d7e180.js:1
t.hydrate @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
Promise.then (async)
35545 @ main-7191483071d7e180.js:1
n @ webpack-e583b1830d643d08.js:1
(anonymous) @ main-7191483071d7e180.js:1
n.O @ webpack-e583b1830d643d08.js:1
(anonymous) @ main-7191483071d7e180.js:1
t @ webpack-e583b1830d643d08.js:1
(anonymous) @ main-7191483071d7e180.js:1
main-7191483071d7e180.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at W (feeds-433f504e5391bc24.js:1:19339)
    at oo (framework-45ce3d09104a2cae.js:1:59415)
    at Wo (framework-45ce3d09104a2cae.js:1:68982)
    at Ku (framework-45ce3d09104a2cae.js:1:112706)
    at Li (framework-45ce3d09104a2cae.js:1:98956)
    at Ni (framework-45ce3d09104a2cae.js:1:98884)
    at Pi (framework-45ce3d09104a2cae.js:1:98747)
    at bi (framework-45ce3d09104a2cae.js:1:95713)
    at framework-45ce3d09104a2cae.js:1:45207
    at t.unstable_runWithPriority (framework-45ce3d09104a2cae.js:1:129349)
re @ main-7191483071d7e180.js:1
fn @ main-7191483071d7e180.js:1
value @ main-7191483071d7e180.js:1
a.componentDidCatch.n.callback @ framework-45ce3d09104a2cae.js:1
ha @ framework-45ce3d09104a2cae.js:1
gu @ framework-45ce3d09104a2cae.js:1
Ri @ framework-45ce3d09104a2cae.js:1
t.unstable_runWithPriority @ framework-45ce3d09104a2cae.js:1
Ql @ framework-45ce3d09104a2cae.js:1
Oi @ framework-45ce3d09104a2cae.js:1
bi @ framework-45ce3d09104a2cae.js:1
(anonymous) @ framework-45ce3d09104a2cae.js:1
t.unstable_runWithPriority @ framework-45ce3d09104a2cae.js:1
Ql @ framework-45ce3d09104a2cae.js:1
Yl @ framework-45ce3d09104a2cae.js:1
Kl @ framework-45ce3d09104a2cae.js:1
hi @ framework-45ce3d09104a2cae.js:1
zo @ framework-45ce3d09104a2cae.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
b @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
o @ 9857-d465aa09f39b4116.js:1
Promise.then (async)
c @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
i @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
(anonymous) @ 9857-d465aa09f39b4116.js:1
gu @ framework-45ce3d09104a2cae.js:1
Ri @ framework-45ce3d09104a2cae.js:1
t.unstable_runWithPriority @ framework-45ce3d09104a2cae.js:1
Ql @ framework-45ce3d09104a2cae.js:1
Oi @ framework-45ce3d09104a2cae.js:1
bi @ framework-45ce3d09104a2cae.js:1
hi @ framework-45ce3d09104a2cae.js:1
es @ framework-45ce3d09104a2cae.js:1
(anonymous) @ framework-45ce3d09104a2cae.js:1
ki @ framework-45ce3d09104a2cae.js:1
os @ framework-45ce3d09104a2cae.js:1
t.hydrate @ framework-45ce3d09104a2cae.js:1
h.default.createElement.callbacks @ main-7191483071d7e180.js:1
fe @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
l @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
P.forEach.e.<computed> @ main-7191483071d7e180.js:1
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
te @ main-7191483071d7e180.js:1
ee @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
l @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
P.forEach.e.<computed> @ main-7191483071d7e180.js:1
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
Promise.then (async)
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
Promise.then (async)
T @ main-7191483071d7e180.js:1
i @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
Z @ main-7191483071d7e180.js:1
t.hydrate @ main-7191483071d7e180.js:1
(anonymous) @ main-7191483071d7e180.js:1
Promise.then (async)
35545 @ main-7191483071d7e180.js:1
n @ webpack-e583b1830d643d08.js:1
(anonymous) @ main-7191483071d7e180.js:1
n.O @ webpack-e583b1830d643d08.js:1
(anonymous) @ main-7191483071d7e180.js:1
t @ webpack-e583b1830d643d08.js:1
(anonymous) @ main-7191483071d7e180.js:1
main-7191483071d7e180.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```



I tried it on Brave and Safari. 

MacOS 13.5
Apple M2

**Comment by Podginator** [comment]
Closing due to age, and the self-hosted nature of Omnivore. Done as a batch action. If this issue still exists, please reopen it.
