### ISSUE TITLE
RangeError: Invalid time zone specified: Etc/Unknown

### ISSUE THREAD

**Issue by francisol** [omnivore-app/omnivore#2787]
When I  add a api key , the console show:
```
RangeError: Invalid time zone specified: Etc/Unknown
    at new DateTimeFormat (<anonymous>)
    at a (915-86c7fc4cd3de12c2.js:1:49151)
    at api-fe70b0bf17e38b00.js:1:21180
    at Array.map (<anonymous>)
    at O (api-fe70b0bf17e38b00.js:1:20819)
    at oo (framework-45ce3d09104a2cae.js:1:59415)
    at Wo (framework-45ce3d09104a2cae.js:1:68982)
    at Ku (framework-45ce3d09104a2cae.js:1:112706)
    at Li (framework-45ce3d09104a2cae.js:1:98956)
    at Ni (framework-45ce3d09104a2cae.js:1:98884)
```

**Comment by jacksonh** [comment]
@francisol this is happening on the web? Can i ask which browser/OS you are on?

**Comment by jacksonh** [comment]
Just adding this here as I see this type of issue referenced: https://support.google.com/chrome/thread/230621092/chrome-version-116-displaying-wrong-timezone-on-linux-computers?hl=en

**Comment by francisol** [comment]
> Just adding this here as I see this type of issue referenced: https://support.google.com/chrome/thread/230621092/chrome-version-116-displaying-wrong-timezone-on-linux-computers?hl=en

solved
