### ISSUE TITLE
Error merging highlights if one highlight has a label attached to it

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#3322]
Video to replicate:  https://www.loom.com/share/dfd149231db94496b677dab5b99512b2

This error is created on the backend: 

```
Error merging highlight null value in column "label_id" violates not-null constraint QueryFailedError: null value in column "label_id" violates not-null constraint
    at PostgresQueryRunner.query (/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:147:21)
    at async /app/packages/api/dist/services/highlights.js:40:30
    at async EntityManager.transaction (/app/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
    at async mergeHighlights (/app/packages/api/dist/services/highlights.js:37:26)
    at async /app/packages/api/dist/resolvers/highlight/index.js:76:30
```

**Comment by sywhb** [comment]
Fixing it now

**Comment by jacksonh** [comment]
Thanks, just found it while testing some client things.
