### ISSUE TITLE
Constant Crash on app open v206.0 - android beta

### ISSUE THREAD

**Issue by Lostendalfah1980** [omnivore-app/omnivore#3964]
This is my first time posting an issue on GitHub so please bare with me.

- **Issue**: crash on open Omnivore v206.0 download from Google Play Store
- **Device**: Pixel 7 Pro
- **OS Version**: Vanilla Ice Cream AP31.240322.027 (Android Beta Latest version as of 5.17.24)
- **Troubleshooting steps taken**: none at this time
- **Logs(?)**: none at this time but can attach if needed

**Comment by muntasimulhaque** [comment]
It crashes for me, too. Can't even open the app. Please fix this.

**Comment by valtoree** [comment]
Me too on p6a, Grapheneos 😭.

Thanks heaps for all ur hard work devs ❤️ by the way. Ty 🙏🙇

**Comment by valtoree** [comment]
App gave me a log
```
type: crash
osVersion: google/bluejay/bluejay:14/AP1A.240505.004/2024051500:user/release-keys
package: app.omnivore.omnivore:2060000
process: app.omnivore.omnivore
processUptime: 1015 + 231 ms
installer: com.android.vending

java.lang.IllegalStateException: Intercom has been initialized incorrectly. Please make sure the first Intercom method you call is initialize() and that you're passing in the correct app ID and API key
	at io.intercom.android.sdk.Intercom$Companion.client(Intercom.kt:1109)
	at app.omnivore.omnivore.core.analytics.EventTracker.registerUser(EventTracker.kt:30)
	at app.omnivore.omnivore.feature.auth.LoginViewModel$registerUser$1.invokeSuspend(LoginViewModel.kt:164)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@deb1258, Dispatchers.Main.immediate]
```

**Comment by muntasimulhaque** [comment]
> It crashes for me, too. Can't even open the app. Please fix this.

Well, with the bug-fix update, the issue's resolved for me. And I believe for everybody else, too. Thanks.

**Comment by Lostendalfah1980** [comment]
> This is my first time posting an issue on GitHub so please bare with me.
> 
> - **Issue**: crash on open Omnivore v206.0 download from Google Play Store
> - **Device**: Pixel 7 Pro
> - **OS Version**: Vanilla Ice Cream AP31.240322.027 (Android Beta Latest version as of 5.17.24)
> - **Troubleshooting steps taken**: none at this time
> - **Logs(?)**: none at this time but can attach if needed
> 
> 

My app is working now with the latest update from the Play Store with a clearing of the app's cache and data and app restart.

**Comment by valtoree** [comment]
Yes update 0.208 has fixed the issue for me. Can close now for me anyway.

**Comment by thiswillbeyourgithub** [comment]
Hi @jacksonh Is it possible to have a github release for this fix? I don't have the playstore and can't find the apk here
